# We will setup on the 10000 block for these
# Note 80-->10080
version: "2"

services:

  fuseki:
    image: fcrepoapix/apix-fuseki:2.4.1
    container_name: fuseki
    ports:
      - "13030:8080"

  fcrepo:
    image: fcrepoapix/apix-fcrepo:4.7.0
    container_name: fcrepo
    ports:
      - "18080:8080"

  indexing:
    image: fcrepoapix/apix-indexing:latest
    container_name: indexing
    env_file: apix.env
    ports:
      - "19090:9090"
    depends_on:
      - fcrepo
      - fuseki
    links:
      - apix:localhost

  acrepo:
    image: fcrepoapix/apix-acrepo:latest
    container_name: acrepo
    ports:
      - "19102:9102"
      - "19103:9103"
      - "19104:9104"
      - "19105:9105"
      - "19106:9106"
      - "19107:9107"
    depends_on:
      - fcrepo
    links:
      - apix:localhost

  apix:
    image: fcrepoapix/apix-core:latest
    container_name: apix
    env_file: apix.env
    ports:
      - "10080:0080"
      - "18081:8081"
    depends_on:
      - fcrepo

  fits:
    image: fcrepoapix/apix-fits:1.0.3
    container_name: fits
    ports:
      - "18082:8080"
